# Generated by Django 4.2.1 on 2023-06-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_is_publish_book_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_published',
            new_name='is_publish',
        ),
    ]
