# Generated by Django 4.2.1 on 2023-06-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_is_published_book_is_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_publish',
            new_name='is_published',
        ),
    ]
